version: '3'

services:
  descanso_garantido:
    container_name: descanso_garantido
    image: localhost/cmake
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./_build:/app/build
      - ./CMakeLists.txt:/app/CMakeLists.txt
    command: bash -c "cd /app/build && cmake .. && cmake --build . && ./DescansoGarantido"